"use client";
import React from "react";
import Image from "next/image";
import styles from "./styles.module.css";
import { useResize } from "../Hooks/use-resize";
import addSharp from "../../image/icon/add-sharp.svg";
import aboutMobile from "../../image/about/imageAboutMobile.webp";
import aboutTablet from "../../image/about/imageAboutTablet.webp";
import aboutDesktop from "../../image/about/imageAboutDesktop.webp";
const About = () => {
  const { isMobile, isTablet, isDesktop } = useResize();
  return (
    <section className={styles.container}>
      <div className={styles.title}>
        a Story that started with
        <span className={styles.titleSpan}>one simple ape</span>
      </div>

      {isMobile ? (
        <div className={styles.infoFirst}>
          <p>WHO GOT</p> <p>FED UP WITH BORING</p> <p>AND HYPOCRITIC</p>
          <p>COMMONPLACE THIS IS</p> <p>HOW THE IDEA OF</p>
          <p>ESCAPING AND DYNAMIC</p>
          <p>JOURNEY ON THE YACHT</p>
        </div>
      ) : (
        <div className={styles.infoFirst}>
          WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW THE
          IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE <p>YACHT</p>
        </div>
      )}
      <div className={styles.iconX}>
        <Image
          priority
          src={addSharp}
          alt='addSharp'
          width={isDesktop ? 36 : 24}
          height={isDesktop ? 36 : 24}
        />
      </div>
      <div className={styles.infoTwo}>
        EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE
        RANDOMLY GENERATED BY USERS
      </div>

      <Image
        priority
        src={isDesktop ? aboutDesktop : isMobile ? aboutMobile : aboutTablet}
        alt='aboutMobile'
        className={styles.imageAbout}
      />
    </section>
  );
};

export default About;
